{
	"cve": {
		"data_type": "CVE",
		"data_format": "MITRE",
		"data_version": "4.0",
		"CVE_data_meta": {
			"ID": "CVE-2022-24961",
			"ASSIGNER": "cve@mitre.org"
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": []
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"url": "https://www.portainer.io/blog/should-you-expose-portainer-or-agent-to-the-internet",
					"name": "https://www.portainer.io/blog/should-you-expose-portainer-or-agent-to-the-internet",
					"refsource": "MISC",
					"tags": []
				},
				{
					"url": "https://github.com/portainer/portainer/issues/6420",
					"name": "https://github.com/portainer/portainer/issues/6420",
					"refsource": "MISC",
					"tags": []
				},
				{
					"url": "https://github.com/portainer/agent/pull/225/commits/a66977c76043fcff4a8f69c4b65988272d27c01f",
					"name": "https://github.com/portainer/agent/pull/225/commits/a66977c76043fcff4a8f69c4b65988272d27c01f",
					"refsource": "MISC",
					"tags": []
				},
				{
					"url": "https://github.com/portainer/agent/compare/2.11.0...2.11.1",
					"name": "https://github.com/portainer/agent/compare/2.11.0...2.11.1",
					"refsource": "MISC",
					"tags": []
				}
			]
		},
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "In Portainer Agent before 2.11.1, an API server can continue running even if not associated with a Portainer instance in the past few days."
				}
			]
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": []
	},
	"impact": {},
	"publishedDate": "2022-02-11T06:15Z",
	"lastModifiedDate": "2022-02-11T06:15Z"
}