{
	"cve": {
		"data_type": "CVE",
		"data_format": "MITRE",
		"data_version": "4.0",
		"CVE_data_meta": {
			"ID": "CVE-2019-25010",
			"ASSIGNER": "cve@mitre.org"
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": []
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"url": "https://github.com/rust-lang-nursery/failure/issues/336",
					"name": "https://github.com/rust-lang-nursery/failure/issues/336",
					"refsource": "MISC",
					"tags": []
				},
				{
					"url": "https://rustsec.org/advisories/RUSTSEC-2019-0036.html",
					"name": "https://rustsec.org/advisories/RUSTSEC-2019-0036.html",
					"refsource": "MISC",
					"tags": []
				}
			]
		},
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "An issue was discovered in the failure crate through 2019-11-13 for Rust. Type confusion can occur when __private_get_type_id__ is overridden."
				}
			]
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": []
	},
	"impact": {},
	"publishedDate": "2020-12-31T10:15Z",
	"lastModifiedDate": "2021-01-01T18:15Z"
}