{
	"cve": {
		"data_type": "CVE",
		"data_format": "MITRE",
		"data_version": "4.0",
		"CVE_data_meta": {
			"ID": "CVE-2020-4952",
			"ASSIGNER": "cve@mitre.org"
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": []
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/192028",
					"name": "ibm-guardium-cve20204952-priv-escalation (192028)",
					"refsource": "XF",
					"tags": []
				},
				{
					"url": "https://www.ibm.com/support/pages/node/6408630",
					"name": "https://www.ibm.com/support/pages/node/6408630",
					"refsource": "CONFIRM",
					"tags": []
				}
			]
		},
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "IBM Security Guardium 11.2 could allow an authenticated user to gain root access due to improper access control. IBM X-Force ID: 192028."
				}
			]
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": []
	},
	"impact": {},
	"publishedDate": "2021-01-27T17:15Z",
	"lastModifiedDate": "2021-01-27T18:56Z"
}