{
	"cve": {
		"data_type": "CVE",
		"data_format": "MITRE",
		"data_version": "4.0",
		"CVE_data_meta": {
			"ID": "CVE-2023-3210",
			"ASSIGNER": "cve@gitlab.com"
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": []
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"url": "https://hackerone.com/reports/2011474",
					"name": "https://hackerone.com/reports/2011474",
					"refsource": "MISC",
					"tags": []
				},
				{
					"url": "https://gitlab.com/gitlab-org/gitlab/-/issues/415074",
					"name": "https://gitlab.com/gitlab-org/gitlab/-/issues/415074",
					"refsource": "MISC",
					"tags": []
				}
			]
		},
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "An issue has been discovered in GitLab affecting all versions starting from 15.11 before 16.1.5, all versions starting from 16.2 before 16.2.5, all versions starting from 16.3 before 16.3.1. An authenticated user could trigger a denial of service when importing or cloning malicious content."
				}
			]
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": []
	},
	"impact": {},
	"publishedDate": "2023-09-01T11:15Z",
	"lastModifiedDate": "2023-09-01T11:47Z"
}